### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by arth1992** [hmert/inline-search#1]
Hello ,
Your search is awesome lightweight and fast.  Can it be case insensitive because whenever i type small alphabet it doesnt search that letter in list containing Capital alphabet.
Hope you will give a quick solution on that

**Comment by ErickXavier** [comment]
Yeah, I would love to see this too.

**Comment by ErickXavier** [comment]
Ok, I just made a [pull request](https://github.com/hmert/inline-search/pull/2) with the proper change to add support to lowercase. Let's hope he accepts :)

**Comment by hmert** [comment]
@ErickXavier Thanks! I've merged. 👏
